### ISSUE TITLE
Error pages

### ISSUE THREAD

**Issue by mike-engel** [krakenjs/lusca#45]
Is there a way to present custom error pages such as a CSRF token mismatch to the user? Right now, express/lusca just prints the stack trace. Having a way to customize the template would be great.

**Comment by jasisk** [comment]
lusca has no opinion on error handling. It follows the express pattern of letting error-handling middleware do what it needs to.

The short explanation: when you call the continuation in a middleware, you can pass it an argument. If that argument is anything but `'route'`, express assumes you're passing along an error and shortcircuits your middleware chain to the next error-handling middleware. An error-handling middleware is just a middleware with an arity of 4 (`err, req, res, next`, for example). Here's the express documentation on [error-handling middleware](http://expressjs.com/starter/faq.html#how-do-you-setup-an-error-handler-).

If lusca csrf validation fails, we just [call the continuation](https://github.com/krakenjs/lusca/blob/f37271ae76120af34bce62ee404550c19bb91f8f/lib/csrf.js#L48) with the 403 you're seeing in the stack trace. The stack trace being printed is just express' default error-handler kicking in.

If you want to do something else, try adding a middleware that does something like this:

``` js
function handleCsrfFailure(err, req, res, next) {
  if (err.statusCode === 403) {
    console.log(err.stack || err);
    return res.send('ugh. csrf mismatch.');
  } else {
    next(err);
  }
}
```

**Comment by jasisk** [comment]
Closing this issue but feel free to continue the conversation with any questions or comments.

**Comment by mike-engel** [comment]
Thanks @jasisk. Seems simple enough—I'll have to try it when I get home.

**Comment by jasisk** [comment]
No problem. Let me know if you have any trouble.
