### ISSUE TITLE
REST API sessionless

### ISSUE THREAD

**Issue by fonzy2013** [krakenjs/lusca#64]
Hi,

I got lusca for "free" from a scaffolding tool.
Sorry for perhaps asking a very stupid question but is it possible to have a RESTful endpoints which doesn't use cookies for sessions in express?

**Comment by jasisk** [comment]
Not a stupid question—no worries. :grinning: 

Yup, certainly possible. Read up a bit on [JWTs](http://jwt.io). Then, check out the [node implementation](https://github.com/auth0/node-jsonwebtoken) or the [express-specific node implementation](https://github.com/auth0/express-jwt) (uses the former).

Falls a bit outside the scope of lusca so I'm closing this but feel free to continue the conversation.

**Comment by tlivings** [comment]
Hi - could you give some more details on what you are trying to do? HATEOAS? Simply disabling the session middleware?
