### ISSUE TITLE
support for CSP's block-all-mixed-content

### ISSUE THREAD

**Issue by turboMaCk** [krakenjs/lusca#69]
It will be nice to have support for: `Content-Security-Policy: block-all-mixed-content`

http://www.w3.org/TR/2015/CR-mixed-content-20151008/
and even
http://www.w3.org/TR/2015/CR-upgrade-insecure-requests-20151008/

Hacky solution:
```javascript
csp: { policy: { '': 'block-all-mixed-content' } }
```

**Comment by jasisk** [comment]
Makes sense to me. :+1:
