### ISSUE TITLE
CSRF token missing for enctype="multipart/form-data"

### ISSUE THREAD

**Issue by erbridge** [krakenjs/lusca#70]
I'm using `lusca` without `krakenjs` and am trying to get CSRF working with an image upload. I am parsing the form later in my route logic using `multer`.

How can I get CSRF to work with this?

**Comment by jasisk** [comment]
`multer` will have to be earlier in the continuation than lusca as it needs to pluck the token off of the body (which isn't parsed until the `multer` middleware).

**Comment by erbridge** [comment]
That's impractical for my use case. Alternatively, is there a built in way to exclude routes from requiring CSRF?

**Comment by jasisk** [comment]
Sure thing. Check out the section on **Route paths** in [the expressjs guide on routing](http://expressjs.com/guide/routing.html). Short version is you can write a regular expression with a [negative lookahead assertion](http://www.regular-expressions.info/lookaround.html). I wrote a small [demo project documenting some middleware registration patterns](https://github.com/jasisk/middleware-patterns) which includes a whitelist pattern leveraging this.

Closing but feel free to continue the conversation.

**Comment by erbridge** [comment]
Ah. Didn't know you could do that. Still not ideal, but it'll suffice. Thanks.
